#!/bin/sh

current_time=$(date "+%Y%m%d%H%M%S")

ssh -T deploy@dcplrhr102 <<EOF
  cd /var/www/proms-qx/releases
  git clone -b master git@github.com:SutterRDD/proms-qx-app.git $current_time
  cd $current_time
  npm install
  ng build --aot --environment=production
  pm2 stop proms-qx
  rm /var/www/proms-qx/current
  ln -s /var/www/proms-qx/releases/$current_time /var/www/proms-qx/current
  pm2 start /var/www/proms-qx/shared/config/pm2.json
  cd /var/www/proms-qx/releases && ls -t1 | tail -n +4 | xargs rm -r
  exit
EOF
